### ISSUE TITLE
This package is not compatible with new expo sdk 49

### ISSUE THREAD

**Issue by ybupro** [Sumit1993/react-native-use-websocket#45]
This library is not compatible with new expo sdk 49. After build a apk, the library is not working correctly, cannot connect server within the same network.
May the author do a update?

Thank you!

**Comment by ybupro** [comment]
not a issue

**Comment by pfndesign** [comment]
you need to enable "usesCleartextTraffic" for Android. use expo-build-properties
```
[
      "expo-build-properties",
      {
        "android": {
          "usesCleartextTraffic": true
        }
      }
    ],
```
